# Assignment Day 3

# 1

In [2]:
import numpy as np

In [4]:
arr1=np.arange(3,50,3)

In [5]:
print(arr1)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48]


# 2

In [7]:
list1=[]
list2=[]

for i in range(5):
    element1=int(input())
    list1.append(element1)
for j in range(5):
    element2=int(input())
    list2.append(element2)

arr2=np.array(list1)
arr3=np.array(list2)
print(arr2)
print(arr3)
arrc=np.concatenate((arr2,arr3))
print(arrc)
print(np.sort(arr2))
print(np.sort(arr3))

1
2
3
4
5
6
7
8
9
0
[1 2 3 4 5]
[6 7 8 9 0]
[1 2 3 4 5 6 7 8 9 0]
[1 2 3 4 5]
[0 6 7 8 9]


# 3

In [10]:
arr4=np.arange(12).reshape(2,2,3)
print(arr4)
print(arr4.ndim)
print(arr4.itemsize)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
3
4


# 4

In [3]:
arr5=np.arange(5)
print(arr5)
print(arr5.ndim)
arr6 = np.expand_dims(arr5, axis=1) #using np.expand_dims
print(arr6)
print(arr6.ndim)
arr5r=arr5[np.newaxis,:]   #using np.newaxis
arr5c=arr5[:,np.newaxis]
print(arr5c)
print(arr5r)

[0 1 2 3 4]
1
[[0]
 [1]
 [2]
 [3]
 [4]]
2
[[0]
 [1]
 [2]
 [3]
 [4]]
[[0 1 2 3 4]]


# 5

In [7]:
arr7=np.square([1,2,3,4])
arr8=np.square([5,6,7,8])
print(arr7)
print(arr8)
print()
print(np.hstack((arr7,arr8)))
print(np.vstack((arr7,arr8)))

[ 1  4  9 16]
[25 36 49 64]

[ 1  4  9 16 25 36 49 64]
[[ 1  4  9 16]
 [25 36 49 64]]


# 6

In [19]:
arr9=np.array([1,2,3,2,1,3,5,4,5,5,6,7,4])
print(np.unique(arr9))
(unique,counts)=np.unique(arr9,return_counts=True)
freq=np.asarray((unique, counts)).T
print(freq)

[1 2 3 4 5 6 7]
[[1 2]
 [2 2]
 [3 2]
 [4 2]
 [5 3]
 [6 1]
 [7 1]]
